Add unit test
exo-addons/task pull request #252
Opened 2020-09-13 00:28 UTC by lbengayed

2020-09-14 15:22 UTC, mkrout commented on services/src/test/java/org/exoplatform/task/service/TaskServiceTest.java
> +    // assertEquals(newTitle, taskCaptor.getValue().getTitle());
?

2020-09-14 15:29 UTC, mkrout requested changes

2020-09-14 15:29 UTC, mkrout commented on services/src/test/java/org/exoplatform/task/service/TaskServiceTest.java
> +*/
Please uncomment or remove commented code

2020-09-14 19:44 UTC, lbengayed commented on services/src/test/java/org/exoplatform/task/service/TaskServiceTest.java
> +    // assertEquals(newTitle, taskCaptor.getValue().getTitle());
done!

2020-09-14 19:45 UTC, lbengayed commented on services/src/test/java/org/exoplatform/task/service/TaskServiceTest.java
> +*/
done

2020-09-15 14:28 UTC, mkrout approved these changes
LGTM

2020-09-16 08:56 UTC, merged