TASK-38545: fixed task search problem when using unified search
exo-addons/task pull request #295
Opened 2021-02-18 16:32 UTC by nidhalnidhal

when searching Tasks in the unified search Bar you cannot find these Tasks due to the fact that there is failing test in the function that formats the result, so i fixed that test case .

2021-02-18 17:25 UTC, ahamdi requested changes

2021-02-18 17:25 UTC, ahamdi commented on task-management/src/main/webapp/vue-app/taskDrawer/components/TaskDrawer.vue
> +
Unneeded cha'ge, please revert it

2021-02-19 09:58 UTC, aelbenney approved these changes, later dismissed

2021-02-19 09:58 UTC, aelbenney commented on task-management/src/main/webapp/vue-app/taskSearch/main.js
> +       results = results.tasks.map(task => {
Please keep it two spaces of indentation.

2021-02-19 09:58 UTC, aelbenney commented on task-management/src/main/webapp/vue-app/taskDrawer/components/TaskDrawer.vue
> +
revert this useless change.

2021-02-19 14:08 UTC, ahamdi approved these changes

2021-02-19 14:30 UTC, merged