Task-47659: projects not visible in space after editing space name
exo-addons/task pull request #600
Opened 2021-08-06 11:55 UTC by AzmiTouil

We should get space by display name to fix the problem

2021-08-06 12:46 UTC, ahamdi requested changes, later dismissed
Could you add a UT for this change

2021-08-11 15:02 UTC, azayati requested changes
See review

2021-08-11 15:02 UTC, azayati commented on integration/pom.xml
> +    <version>3.3.x-maintenance-SNAPSHOT</version>
this modifications should not appear IMHO, should be checked

2021-08-11 15:31 UTC, azayati approved these changes
LGTM

2021-08-11 15:48 UTC, merged