Task-47896: Fix edit project - refresh issues
exo-addons/task pull request #621
Opened 2021-08-20 15:54 UTC by NaderSai

Problem: when changing the project from Project Tab it doesn't update in the board/list view. 
How it was solved: by sending event when updating the project to the board event to update it directly in the board view. And by affecting the false value to isPersonnalTask to select the right div for the list view.

2021-08-24 07:47 UTC, rdenarie commented on task-management/src/main/webapp/vue-app/tasks-management/components/tasks/TasksListItem.vue
> +    this.$root.$on('update-task-widget-list', task => {
Can you explain this part ? I'm not sure to understand.

2021-08-26 08:32 UTC, NaderSai commented on task-management/src/main/webapp/vue-app/tasks-management/components/tasks/TasksListItem.vue
> +    this.$root.$on('update-task-widget-list', task => {
at the top (line 42) there is a condition in the div in which we find the project name implementation. According to the written code we can enter to this div only if isPersonnalTask value is false. so when we receive the event update-task-widget-list which is related to the updateTask method we must put isPersonnalTask to false to consider the update directly without need to refresh the page.

2021-08-26 13:16 UTC, rdenarie requested changes
Can you rebase your pr to have only your commit ?

2021-08-26 13:37 UTC, NaderSai commented
> Can you rebase your pr to have only your commit ?

done !

2021-08-26 14:02 UTC, rdenarie requested changes

2021-08-26 14:02 UTC, rdenarie commented on task-management/src/main/webapp/vue-app/taskDrawer/components/TaskDrawerComponents/TaskProject.vue
> +          .catch(e => {
this catch generate a js error :
I create 2 spaces
I add a task in the space project
I reopen the task, and choose another project, and then 
![image](https://user-images.githubusercontent.com/807839/130976110-a2c697bf-6e67-4e59-87bd-a9a5d812324a.png)

2021-08-26 14:02 UTC, rdenarie commented on task-management/src/main/webapp/vue-app/tasks-management/components/tasks/TasksListItem.vue
> +      }
This code is not called when updating a task project. I think it should be removed

2021-08-27 06:53 UTC, rdenarie requested changes
Can you rebase the PR to remove other commits ?

2021-08-27 08:23 UTC, NaderSai commented on task-management/src/main/webapp/vue-app/tasks-management/components/tasks/TasksListItem.vue
> +      }
> Can you rebase the PR to remove other commits ?

done

2021-08-27 14:14 UTC, rdenarie requested changes
One thing is missing, can you put the PR description in the first commit message ?
Thanks

2021-08-27 14:55 UTC, rdenarie approved these changes

2021-08-27 14:55 UTC, merged