Task-48085: Task assigning is not working.
exo-addons/task pull request #627
Opened 2021-08-27 11:29 UTC by lbengayed

In the taskDrawer the receive event was updateTaskAssignment, so we should change the name of emitted event in taskAssignment to updateTaskAssignment.

2021-08-27 14:33 UTC, rdenarie requested changes
Can you explain your modification ?

You should fill the PR description and the commit message to answer WHY ? and HOW ? questions.

Thanks

2021-08-27 14:37 UTC, azayati requested changes

2021-08-27 14:37 UTC, azayati commented on task-management/src/main/webapp/vue-app/taskDrawer/components/TaskDrawer.vue
> +              @updateTaskAssignement="updateTaskAssignee($event)"
In english it should be "updateTaskAssignment", so I think that you should change the name of emitted event instead

2021-08-30 11:47 UTC, rdenarie requested changes
Can you update your commit message and PR description to follow the commit message best practises :
https://developer.exoplatform.org/#id-commits-messages-best-practices
The commit message should be

Title
Empty line
Description answering question WHY ? and HOW ?

Thanks

2021-08-30 13:53 UTC, rdenarie submitted a review, later dismissed

2021-08-30 15:12 UTC, azayati approved these changes
LGTM

2021-08-30 15:15 UTC, azayati requested changes
@lbengayed https://github.com/exoplatform/task/blob/8e3bf1f92cde73889972cd967ff0cab80fdee47d/task-management/src/main/webapp/vue-app/taskDrawer/components/TaskDrawerComponents/TaskAssignment.vue#L275 you have also this reference to updateTaskAssignement, should it be changed also ?

2021-08-30 15:48 UTC, lbengayed commented
> @lbengayed
> 
> https://github.com/exoplatform/task/blob/8e3bf1f92cde73889972cd967ff0cab80fdee47d/task-management/src/main/webapp/vue-app/taskDrawer/components/TaskDrawerComponents/TaskAssignment.vue#L275
> 
> you have also this reference to updateTaskAssignement, should it be changed also ?

yes thnx @azayati

2021-08-30 15:58 UTC, azayati requested changes
@lbengayed 
When seeing commits I think that this commit https://github.com/exoplatform/task/commit/8e3bf1f92cde73889972cd967ff0cab80fdee47d#diff-d684f376b0426354ae571baaa57cad44ecf876ae10e59323455ca4762c3c3c0e has overriden some files of the commit just before, can you verify them please especially TasksViewDashboard.vue TaskPriority.vue? cc @SaraBoutej

2021-08-30 16:18 UTC, lbengayed commented
> TasksViewDashboard.vue

the root cause of this bug was this commit 8e3bf1f#diff-d684f376b0426354ae571baaa57cad44ecf876ae10e59323455ca4762c3c3c0e , i fix the problems of priority and assigning

2021-08-31 07:07 UTC, rdenarie approved these changes, later dismissed

2021-08-31 07:39 UTC, azayati submitted a review, later dismissed
LGTM

@lbengayed we should as recommended verify the last commit with @SaraBoutej to avoid other regressions cc @rdenarie

2021-08-31 09:02 UTC, SaraBoutej approved these changes, later dismissed
LGTM

2021-08-31 12:01 UTC, SaraBoutej approved these changes

2021-08-31 14:27 UTC, azayati requested changes
@lbengayed the PR should be created on feature/maintenance before

2021-09-01 14:20 UTC, closed without merging