Task-38356 :  Add external tag in assignee, coworker and mention in comments.
exo-addons/task pull request #65
Opened 2020-12-21 16:32 UTC by ahmadmido

…

2020-12-22 08:53 UTC, ahamdi commented
This PR should be either on feature/maintenance or on your FT branch. You should not create PRs on develop directly

2020-12-22 11:16 UTC, azayati requested changes
see review

2020-12-22 11:16 UTC, azayati commented on services/src/main/java/org/exoplatform/task/rest/TaskRestService.java
> +  public Response findUsersToMention(@ApiParam(value = "Query", required = true) @PathParam("query") String query, @ApiParam(value = "Lang", required = true) @PathParam("lang") String lang) throws Ex
can you detect the locale directly from @Context HttpServletRequest request ?

2020-12-22 11:16 UTC, azayati commented on services/src/main/java/org/exoplatform/task/util/TaskUtil.java
> +  public static boolean isMemberOfExternalGroup(String userId) throws Exception{
Is it possible to user the method Util.isExternal from social ?

2020-12-22 19:35 UTC, azayati requested changes
See review

2020-12-22 19:35 UTC, azayati commented on services/src/main/java/org/exoplatform/task/service/TaskService.java
> +    public boolean isExternal(String userId) ;
Revert this modification

2020-12-22 19:39 UTC, azayati requested changes
See review

2020-12-22 19:39 UTC, azayati commented on services/src/main/java/org/exoplatform/task/service/TaskService.java
> +
format code

2020-12-23 08:37 UTC, azayati approved these changes
LGTM after QA validation

2020-12-23 11:55 UTC, merged