Task-49264: Space members shouldn't be able to create projects
exo-addons/task pull request #694
Opened 2021-10-06 09:26 UTC by AzmiTouil

Restrict project creation in space for space managers only.

2021-10-06 16:28 UTC, ahamdi requested changes

2021-10-06 16:28 UTC, ahamdi commented on services/src/main/java/org/exoplatform/task/rest/ProjectRestService.java
> +  @ApiOperation(value = "check if the current user can create a project in the given space", httpMethod = "GET", response = Response.class, notes = "This checks if the current user can create a proje
Could you check if there is already an endpoint on Social side for checking this ?

2021-10-06 16:28 UTC, ahamdi commented on task-management/src/main/webapp/vue-app/tasks-management/components/Project/ProjectListToolbar.vue
> +        return this.$projectService.canCreateProject().then(canCreateProject => {
Check if there is not already a service that returns the same info

2021-10-07 10:04 UTC, AzmiTouil commented on services/src/main/java/org/exoplatform/task/rest/ProjectRestService.java
> +  @ApiOperation(value = "check if the current user can create a project in the given space", httpMethod = "GET", response = Response.class, notes = "This checks if the current user can create a proje
checked, there is no api for this.
Do you propose to add one in social API?

2021-10-07 10:32 UTC, ahamdi commented on services/src/main/java/org/exoplatform/task/rest/ProjectRestService.java
> +  @ApiOperation(value = "check if the current user can create a project in the given space", httpMethod = "GET", response = Response.class, notes = "This checks if the current user can create a proje
Yep a generic one, to check if a user is a manger/super manager of a space, we need to return the list of space managers of a space in org/exoplatform/social/rest/api/SpaceRestResources.java and implementation in org/exoplatform/social/rest/impl/space/SpaceRestResourcesV1.java

2021-10-07 10:33 UTC, ahamdi commented on services/src/main/java/org/exoplatform/task/rest/ProjectRestService.java
> +  @ApiOperation(value = "check if the current user can create a project in the given space", httpMethod = "GET", response = Response.class, notes = "This checks if the current user can create a proje
@AzmiTouil please make sure that the new endpoint is well secured, just space members and managers/supermanagers are able to access such endpoint

2021-10-07 12:11 UTC, ahamdi commented on services/src/main/java/org/exoplatform/task/rest/ProjectRestService.java
> +  @ApiOperation(value = "check if the current user can create a project in the given space", httpMethod = "GET", response = Response.class, notes = "This checks if the current user can create a proje
@AzmiTouil it seems there is already an endpoint. But I think that we need to improve and retrieve that information from the space DTO object. 
We initialize the task components based on different level of memberships that we receive from the Space DTO object

2021-10-07 19:38 UTC, ahamdi approved these changes

2021-10-12 14:02 UTC, merged