Task-43333: Regression - bad display(alignment-UI glitches) of task changes in change history
exo-addons/task pull request #734
Opened 2022-01-05 11:10 UTC by Montassar-Hamadi

Problem: a bad alignment of the task changes in the task's changes tab is displayed.
Fix: Task changes should be well displayed with aligned.

2022-01-05 17:08 UTC, rdenarie reviewed
deleted comment

2022-01-05 17:09 UTC, rdenarie requested changes
Hello
This PR seems not ok.
In the associated task, there is 3 differents PR to cherry pick.
As I can see you get only the last one

2022-01-06 10:59 UTC, Montassar-Hamadi commented
@rdenarie the first and the 2nd PR changes are combined into this PR's first commit, the 2nd commit is related to the 3rd PR changes.

2022-01-06 12:58 UTC, rdenarie approved these changes

2022-01-06 12:58 UTC, merged