can't remove start date of a task
exo-addons/task pull request #741
Opened 2022-01-10 10:44 UTC by hthabti

issue: start date can't be removed when clicking on 'none' label from the datepicker
fix: add else-if statement to handle user's input on the datepicker when the value of entered label = 'none'

2022-01-10 12:29 UTC, rdenarie requested changes

2022-01-10 12:29 UTC, rdenarie commented on task-management/src/main/webapp/vue-app/taskDrawer/components/TaskDrawer.vue
>            console.error(e);
Remove console.log

2022-01-10 12:29 UTC, rdenarie commented on task-management/src/main/webapp/vue-app/taskDrawer/components/TaskDrawer.vue
> +            message: 'Error message to find'
Here you have to change the error message to use the good one, with i18n

2022-01-11 12:49 UTC, rdenarie submitted a review, later dismissed

2022-01-12 09:41 UTC, rdenarie reviewed
Please rebase and fixe the conflict

2022-01-12 17:37 UTC, hbenali commented on task-management/src/main/webapp/vue-app/taskDrawer/components/TaskDrawer.vue
>          }).catch(e => {
```suggestion
        }).catch(() => {
```
`e` variable is no more used.

2022-01-14 09:05 UTC, hbenali approved these changes

2022-01-14 09:09 UTC, merged