TASK-53005: In Tasks application, when updating the project name, the updates are not immediately made and the display of the project is lost after updating.
exo-addons/task pull request #745
Opened 2022-01-13 16:53 UTC by IlhemEssaadi

ISSUES : In Tasks application, when updating the project name, the updates are not immediately made and the display of the project is lost after updating.
FIX : the problem is in the reset method which is launched when we refresh the page and it fixed by fixing the condition .

2022-01-14 10:28 UTC, rdenarie requested changes
This PR revert a change done few day ago.

2022-01-17 08:34 UTC, hbenali commented
You better shorten the pull request title, it's too long

2022-01-17 13:38 UTC, rdenarie approved these changes

2022-01-17 13:39 UTC, rdenarie requested changes
Can you shorter the PR title ?

In addition can you explain in the description how you fix the problem ? What is the modification. ? currently you explain only where is the problem but not what it is

2022-01-18 08:44 UTC, rdenarie approved these changes

2022-01-18 09:03 UTC, merged